
const GET_CHAT = "GET_CHAT"
const COUNT_CHAT_NAV = "COUNT_CHAT_NAV"
const VIEW_CHAT = "VIEW_CHAT"
const NOTIFI_CHAT = "NOTIFI_CHAT"
const NEW_CHAT = "NEW_CHAT"


export {
   GET_CHAT , COUNT_CHAT_NAV , VIEW_CHAT , NOTIFI_CHAT , NEW_CHAT
}